<a href="https://colab.research.google.com/github/Rohansiddu/Python-Course-Work/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print("1 dim",arr1, sep='\n', end ='\n\n')

arr2 = np.array([[1,2,3],[4,5,6]])
print("2 dim",arr2, sep='\n', end ='\n\n')

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,9,7]])
print("multi dim",arr3, sep='\n', end ='\n\n')

1 dim
[1 2 3 4 5]

2 dim
[[1 2 3]
 [4 5 6]]

multi dim
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 9 7]]



In [ ]:
zeros = np.zeros((4,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
ones = np.ones((4,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
identity= np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
full_array = np.full((10,5),"aa")
print(full_array)

[['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']
 ['aa' 'aa' 'aa' 'aa' 'aa']]


In [ ]:
range_arr = np.arange(1,100,2)
print(range_arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
line_space = np.linspace(0,10,5)
print(line_space)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
rand_int=np.random.randint(50,90,(4,4))
print(rand_int)

[[82 79 61 71]
 [86 70 67 74]
 [68 85 77 76]
 [56 54 69 67]]


In [ ]:
rand_int=np.random.randint(20,26)
print(rand_int)

23


In [ ]:
rand_int=np.random.randint(60)
print(rand_int)

48


In [ ]:
rand_choice=np.random.choice(['html','python','java','css'],3)
print(rand_choice)

['css' 'html' 'html']


In [ ]:
np.random.seed(10)

rand_arr = np.random.randint(6)
print(rand_arr)

1


In [ ]:
arr = np.array([[1,2],[4,5],[8,7],[1,2],[4,5]])
print(arr.shape)

(5, 2)


In [ ]:
reshaped = arr.reshape(2,5)
print(reshaped)

[[1 2 4 5 8]
 [7 1 2 4 5]]


In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4]])
flattened = a.flatten()
print(flattened)

[1 2 3 4 1 2 3 4]


In [9]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[2,0])
print(matrix[0,1])

print(matrix[0:3,1])
print(matrix[1:3,2])

print(matrix[0:3,0:2])
print(matrix[1:3,1:3])

7
2
[2 5 8]
[6 9]
[[1 2]
 [4 5]
 [7 8]]
[[5 6]
 [8 9]]


In [15]:
arr=np.array([[9,4,16],[25,36,49],[64,81,100]])
print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr ** 2)
print(f'sqrt:{np.sqrt(arr)}')

[[ 10   5  17]
 [ 26  37  50]
 [ 65  82 101]]
[[ 8  3 15]
 [24 35 48]
 [63 80 99]]
[[ 18   8  32]
 [ 50  72  98]
 [128 162 200]]
[[   81    16   256]
 [  625  1296  2401]
 [ 4096  6561 10000]]
sqrt:[[ 3.  2.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [16]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

384
42.666666666666664
36.0


In [17]:
print(np.min(arr))
print(np.max(arr))

4
100


In [18]:
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))

42.666666666666664
994.2222222222222
31.531289574361246


In [21]:
arr=np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [22]:
arr=np.array([10,20,30,40,50])
print(arr%20==0)
print(arr[arr%20==0])

[False  True False  True False]
[20 40]


In [23]:
arr=np.array([3,1,4,5,1,6,3,9,2,6])
sorted_arr=np.sort(arr)
print(sorted_arr)

[1 1 2 3 3 4 5 6 6 9]


In [24]:
unique_vals = np.unique(arr)
print(unique_vals)

[1 2 3 4 5 6 9]


In [27]:
arr = np.array([10,20,30])
view_arr=arr.view()
view_arr[0] = 100
print(arr,view_arr)

copy_arr=arr.copy()
copy_arr[0] = 200
print(arr,copy_arr)

[100  20  30] [100  20  30]
[100  20  30] [200  20  30]


alzebra..........

In [29]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [30]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [31]:
vertical_stack = np.vstack((A,B))
horizontal_stack = np.hstack((A,B))
print(vertical_stack)
print(horizontal_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [37]:
split_arr = np.split(np.array([1,2,3,4,5,6]),3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]
